apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: application
  labels:
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: app2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: application
  labels:
    app: app2
spec:
  selector:
    app: app2
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app2
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - application
  selector:
    matchLabels:
      app: app2
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
