name: Terraform

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/live/dev/app-cluster

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/live/dev/app-cluster
